# Generated by Django 4.1.5 on 2023-02-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdbID', models.CharField(default='0', max_length=4)),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
