# Generated by Django 4.1.5 on 2023-02-23 06:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TmDbid', models.CharField(default='0', max_length=8)),
                ('title', models.CharField(default='No Title', max_length=100)),
                ('release_date', models.CharField(default='No Date', max_length=32)),
                ('overview', models.CharField(default='', max_length=500)),
                ('popularity', models.IntegerField(default=0)),
                ('poster_path', models.CharField(default='', max_length=500)),
                ('genre_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('rating', models.IntegerField(default=0)),
                ('vote_average', models.IntegerField(default=0)),
                ('cast', models.JSONField()),
                ('crew', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='defaultUsername', max_length=30)),
                ('user_films_dict', models.JSONField(default=dict)),
                ('movies', models.ManyToManyField(to='MovieApp.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ManyToManyField(to='MovieApp.movie')),
            ],
        ),
    ]
