# Generated by Django 4.1.5 on 2023-02-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_films_dict',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='No Title', max_length=50),
        ),
    ]
