# Generated by Django 4.1.5 on 2023-02-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_films_dict',
        ),
    ]
