# Generated by Django 4.1.5 on 2023-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_ids',
        ),
        migrations.AlterField(
            model_name='movie',
            name='TmDbid',
            field=models.CharField(blank=True, default='0', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(default='defaultUsername', max_length=50),
        ),
    ]
