# Generated by Django 4.1.5 on 2023-02-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_remove_movie_cast_remove_movie_crew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_films_dict',
            field=models.JSONField(default=dict),
        ),
    ]
