# Generated by Django 4.1.5 on 2023-02-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_user_user_films_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.JSONField(default=list),
        ),
    ]
