# Generated by Django 4.1.5 on 2023-03-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_alter_movie_tmdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movie_reccs_dict',
            field=models.JSONField(default=dict),
        ),
    ]
