# Generated by Django 4.1.5 on 2023-03-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_user_movie_reccs_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moviereccs',
            field=models.ManyToManyField(related_name='reccomended_by', to='MovieApp.movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(related_name='movie_reccs', to='MovieApp.movie'),
        ),
    ]
