# Generated by Django 4.1.5 on 2023-04-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_user_moviereccs_alter_user_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='moviereccs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movies',
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
