# Generated by Django 4.1.6 on 2023-05-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0006_remove_user_moviereccs_remove_user_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reccs_info_dict',
            field=models.JSONField(default=dict),
        ),
    ]
